const stages=[
 {id:1,name:'Abwertung in Sprache',short:'Sprache',color:'#20a36a',weight:1,description:'Stereotype, Gerüchte und Verharmlosung antisemitischer Sprache.'},
 {id:2,name:'Distanzierung & Ausschluss',short:'Distanz',color:'#82c751',weight:1.2,description:'Soziale Vermeidung und die Akzeptanz von Ausgrenzung.'},
 {id:3,name:'Diskriminierung',short:'Diskriminierung',color:'#eabf35',weight:1.5,description:'Ungleiche Rechte, Chancen oder Dienstleistungen.'},
 {id:4,name:'Gewaltakzeptanz',short:'Gewalt',color:'#e98536',weight:2,description:'Rechtfertigung von Angriffen oder Sachbeschädigung.'},
 {id:5,name:'Entmenschlichung',short:'Entmenschlichung',color:'#df5360',weight:2.5,description:'Billigung schwerster Gewalt oder Entfernung jüdischen Lebens.'}
];
const questions=[
 [1,'Jüdischen Menschen wird in Verschwörungserzählungen oft pauschal Einfluss auf Medien, Wirtschaft oder Politik zugeschrieben. Solche Erzählungen sind nachvollziehbar.'],[1,'Antisemitische Witze im privaten Kreis sind harmlos, wenn niemand direkt betroffen ist.'],[1,'Die Erinnerung an die Shoah wird von Jüdinnen und Juden genutzt, um sich Vorteile zu verschaffen.'],[1,'Jüdinnen und Juden tragen als Gruppe Verantwortung für gesellschaftliche Probleme.'],
 [2,'Ich fände es unangenehm, wenn in meiner Nachbarschaft eine Synagoge oder ein jüdisches Gemeindezentrum entstünde.'],[2,'Es ist besser, wenn jüdische Menschen unter sich bleiben, um Konflikte zu vermeiden.'],[2,'Ich würde nicht wollen, dass mein Kind enge Freundschaften mit jüdischen Kindern schließt.'],[2,'Eine Kippa oder ein anderer jüdischer Ausdruck sollte im öffentlichen Raum besser nicht sichtbar sein.'],
 [3,'Arbeitgebende oder Vermietende dürfen jüdische Bewerber:innen anders beurteilen als andere.'],[3,'Jüdischen Organisationen sollte der Zugang zu bestimmten öffentlichen Räumen oder Institutionen eingeschränkt werden.'],[3,'Jüdische Menschen sollten in politischen oder medialen Berufen begrenzt werden, damit sie nicht zu viel Einfluss haben.'],[3,'Es ist akzeptabel, einzelne jüdische Menschen für Entscheidungen der israelischen Regierung verantwortlich zu machen.'],
 [4,'Sachbeschädigung an Synagogen oder jüdischen Einrichtungen kann als politische Reaktion gerechtfertigt sein.'],[4,'Körperliche Übergriffe auf sichtbar jüdische Personen sind unter Umständen nachvollziehbar.'],[4,'Gewaltvolle Proteste gegen jüdische Geschäfte oder Einrichtungen sind ein legitimes politisches Mittel.'],[4,'Wer jüdische Symbole sichtbar trägt, trägt Mitverantwortung für mögliche Angriffe.'],
 [5,'Eine Gesellschaft wäre besser, wenn jüdisches Leben darin keinen Platz hätte.'],[5,'Schwere Gewalt gegen jüdische Menschen kann unter politischen oder historischen Umständen gerechtfertigt sein.'],[5,'Die erzwungene Entfernung jüdischer Menschen aus einem Land wäre eine akzeptable Lösung für Konflikte.'],[5,'Jüdische Menschen sind weniger schützenswert als andere Menschen.']
].map(([stage,text],i)=>({id:i+1,stage,text}));
const answers=['Stimme überhaupt nicht zu','Stimme eher nicht zu','Unentschieden / weiß nicht','Stimme eher zu','Stimme voll zu'];
let current=0,values=Array(questions.length).fill(null);
const $=id=>document.getElementById(id);
function renderStages(){ $('stage-overview').innerHTML=stages.map(s=>`<div class="stage-chip" style="--color:${s.color}"><strong>${s.id}. ${s.short}</strong>${s.description}</div>`).join(''); }
function renderQuestion(){const q=questions[current],s=stages[q.stage-1];$('question-count').textContent=`Aussage ${current+1} von ${questions.length}`;$('stage-label').textContent=`Bereich ${q.stage}: ${s.short}`;$('question-stage').textContent=s.name;$('question-text').textContent=q.text;$('progress-bar').style.width=`${((current+1)/questions.length)*100}%`;$('back-button').disabled=current===0;$('next-button').textContent=current===questions.length-1?'Auswertung anzeigen →':'Weiter →';$('next-button').disabled=values[current]===null;$('answers').innerHTML='<legend>Wie sehr stimmst du zu?</legend>'+answers.map((a,i)=>`<label class="answer"><input type="radio" name="answer" value="${i+1}" ${values[current]===i+1?'checked':''}><span>${a}</span></label>`).join('');document.querySelectorAll('input[name="answer"]').forEach(input=>input.addEventListener('change',e=>{values[current]=Number(e.target.value);$('next-button').disabled=false;}));}
function calculate(){const groups=stages.map(s=>{const qs=questions.filter(q=>q.stage===s.id);const sum=qs.reduce((acc,q)=>acc+values[q.id-1],0);return{...s,percent:Math.round(((sum-qs.length)/(qs.length*4))*100),weighted:sum*s.weight};});const raw=groups.reduce((a,g)=>a+g.weighted,0),min=stages.reduce((a,s)=>a+4*s.weight,0),max=stages.reduce((a,s)=>a+20*s.weight,0);return{groups,score:Math.round(1+((raw-min)/(max-min))*124)};}
function feedback(score){if(score<=25)return['Du weist die abgefragten Aussagen überwiegend zurück.','Das ist ein Hinweis auf eine klare Distanz zu antisemitischen Stereotypen und Gewaltlegitimation. Ein hilfreicher nächster Schritt ist Zivilcourage: problematische Witze, Pauschalisierungen und Verschwörungserzählungen im Alltag respektvoll ansprechen.'];if(score<=50)return['Es zeigen sich einzelne Anknüpfungspunkte für stereotype oder ausgrenzende Deutungen.','Das Ergebnis ist keine Festlegung deiner Haltung. Prüfe besonders Verallgemeinerungen über jüdische Menschen, die Verharmlosung von Sprache und die Verwechslung von Menschen mit der Politik eines Staates.'];if(score<=75)return['Mehrere Antworten deuten auf einen deutlichen Reflexionsbedarf hin.','Antisemitische Deutungsmuster können Menschen verletzen und gesellschaftliche Ausgrenzung legitimieren. Beschäftige dich mit der IHRA-Arbeitsdefinition, Perspektiven jüdischer Stimmen und der Unterscheidung zwischen sachbezogener Kritik und Kollektivzuschreibung.'];return['Die Zustimmung zu Aussagen, die Diskriminierung oder Gewalt legitimieren, ist ernst zu nehmen.','Das Instrument kann keine Diagnose stellen. Gewalt oder ihre Rechtfertigung ist nie akzeptabel. Suche ein vertrauliches Gespräch, etwa über eine lokale Beratungsstelle oder eine professionelle psychosoziale Beratung, um die Antworten kritisch zu reflektieren.'];}
function showResults(){const {groups,score}=calculate(),[title,text]=feedback(score);$('quiz').hidden=true;$('result').hidden=false;$('score-value').textContent=score;$('result-summary').textContent=title;$('needle').style.transform=`rotate(${-90+(score-1)/124*180}deg)`;$('breakdown-bars').innerHTML=groups.map(g=>`<div class="breakdown-row"><div class="breakdown-label"><span>${g.id}. ${g.name}</span><strong>${g.percent}%</strong></div><div class="bar"><span style="--color:${g.color};width:${g.percent}%"></span></div></div>`).join('');$('reflection').innerHTML=`<h3>Einordnung</h3><p>${text}</p>`;$('result').focus();}
$('start-button').addEventListener('click',()=>{$('intro').hidden=true;$('methodik').hidden=true;$('quiz').hidden=false;renderQuestion();$('quiz').scrollIntoView({behavior:'smooth'});});$('back-button').addEventListener('click',()=>{if(current>0){current--;renderQuestion();}});$('next-button').addEventListener('click',()=>{if(values[current]===null)return;if(current<questions.length-1){current++;renderQuestion();}else showResults();});$('restart-button').addEventListener('click',()=>{current=0;values.fill(null);$('result').hidden=true;$('intro').hidden=false;$('methodik').hidden=false;window.scrollTo({top:0,behavior:'smooth'});});$('print-button').addEventListener('click',()=>window.print());renderStages();
